# Generated by Django 5.2.7 on 2026-01-13 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_district')),
            ],
        ),
    ]
