# Generated by Django 5.2.7 on 2025-12-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_resortowner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.CharField(max_length=191, unique=True)),
                ('owner_phone', models.CharField(max_length=15)),
                ('licence_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('login_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
