# Generated by Django 5.2.7 on 2025-12-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_resortowner',
            name='licence_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AlterField(
            model_name='tbl_resortowner',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_resortowner',
            name='login_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
