# Generated by Django 5.2.7 on 2025-12-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0002_alter_tbl_resortowner_license_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_resortowner',
            name='login_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
