# Generated by Django 5.2.7 on 2025-12-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0003_remove_tbl_resortowner_license_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_resortowner',
            name='licence_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tbl_resortowner',
            name='login_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
