# Generated by Django 5.2.7 on 2026-01-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0004_alter_tbl_resortowner_licence_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=191, unique=True)),
                ('customer_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('login_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
