# Generated by Django 5.2.7 on 2026-01-05 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0005_tbl_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_resortowner',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guestapp.tbl_login', unique=True),
        ),
    ]
