# Generated by Django 5.2.7 on 2026-01-09 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0006_alter_tbl_resortowner_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customer',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guestapp.tbl_login', unique=True),
        ),
    ]
