# Generated by Django 5.2.7 on 2026-01-19 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestapp', '0008_alter_tbl_customer_login_id_and_more'),
        ('resortownerapp', '0008_remove_tbl_package_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_packagecustomizerequest',
            fields=[
                ('package_customize_id', models.AutoField(primary_key=True, serialize=False)),
                ('customize_description', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_customer')),
                ('package_details_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resortownerapp.tbl_packagedetails')),
                ('package_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resortownerapp.tbl_package')),
            ],
        ),
    ]
