# Generated by Django 5.2.7 on 2026-01-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
        ('resortownerapp', '0008_remove_tbl_package_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_packagecustomizerequest',
            name='package_details_id',
        ),
        migrations.CreateModel(
            name='tbl_customizeitem',
            fields=[
                ('customize_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('package_customize_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerapp.tbl_packagecustomizerequest')),
                ('package_details_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resortownerapp.tbl_packagedetails')),
            ],
        ),
    ]
