# Generated by Django 5.2.7 on 2026-01-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_remove_tbl_packagecustomizerequest_package_details_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customizeitem',
            name='status',
            field=models.CharField(blank=True, default='Added', max_length=50, null=True),
        ),
    ]
