# Generated by Django 5.2.7 on 2026-01-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_alter_tbl_customizeitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_packagecustomizerequest',
            name='customize_description',
        ),
    ]
