# Generated by Django 5.2.7 on 2026-01-21 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_remove_tbl_packagecustomizerequest_customize_description'),
        ('guestapp', '0008_alter_tbl_customer_login_id_and_more'),
        ('resortownerapp', '0008_remove_tbl_package_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_status', models.CharField(blank=True, default='Pending', max_length=50, null=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_customer')),
                ('package_customize_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerapp.tbl_packagecustomizerequest')),
                ('resort_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resortownerapp.tbl_resort')),
            ],
        ),
    ]
