# Generated by Django 5.2.7 on 2026-01-27 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0006_tbl_payment'),
        ('resortownerapp', '0008_remove_tbl_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='package_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resortownerapp.tbl_package'),
        ),
    ]
