# Generated by Django 5.2.7 on 2026-01-29 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0007_tbl_booking_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerapp.tbl_payment'),
        ),
    ]
