# Generated by Django 5.2.7 on 2026-02-16 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_tbl_booking_payment_id'),
        ('guestapp', '0008_alter_tbl_customer_login_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_resortowner'),
        ),
    ]
