# Generated by Django 5.2.7 on 2025-12-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_resort',
            fields=[
                ('resort_id', models.AutoField(primary_key=True, serialize=False)),
                ('resort_name', models.CharField(max_length=100)),
                ('resort_address', models.CharField(max_length=255)),
                ('resort_phone', models.CharField(max_length=15)),
                ('resort_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('category_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
