# Generated by Django 5.2.7 on 2026-01-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortownerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('resort_id', models.IntegerField(blank=True, null=True)),
                ('package_name', models.CharField(max_length=100)),
                ('package_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('duration', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_includes', models.TextField(blank=True, null=True)),
                ('max_people', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
    ]
