# Generated by Django 5.2.7 on 2026-01-16 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_tbl_location'),
        ('guestapp', '0008_alter_tbl_customer_login_id_and_more'),
        ('resortownerapp', '0002_tbl_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_package',
            name='package_includes',
        ),
        migrations.AlterField(
            model_name='tbl_package',
            name='resort_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resortownerapp.tbl_resort'),
        ),
        migrations.AlterField(
            model_name='tbl_resort',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_category'),
        ),
        migrations.AlterField(
            model_name='tbl_resort',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_location'),
        ),
        migrations.AlterField(
            model_name='tbl_resort',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_resortowner'),
        ),
        migrations.AlterField(
            model_name='tbl_resort',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='tbl_packagedetails',
            fields=[
                ('package_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_detail_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortownerapp.tbl_package')),
            ],
        ),
    ]
