# Generated by Django 5.2.7 on 2026-01-16 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortownerapp', '0003_remove_tbl_package_package_includes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_package',
            name='package_details_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resortownerapp.tbl_packagedetails'),
        ),
    ]
