# Generated by Django 5.2.7 on 2026-01-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortownerapp', '0004_tbl_package_package_details_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_package',
            name='price',
        ),
        migrations.AddField(
            model_name='tbl_package',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
