# Generated by Django 5.2.7 on 2026-01-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortownerapp', '0005_remove_tbl_package_price_tbl_package_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_package',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
