# Generated by Django 5.2.7 on 2026-01-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortownerapp', '0006_tbl_package_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_package',
            name='package_details_id',
        ),
    ]
