# Generated by Django 5.2.7 on 2026-01-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortownerapp', '0007_remove_tbl_package_package_details_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_package',
            name='price',
        ),
    ]
